jQuery(document).ready(function($){
$(".banner1").remove();
$(".banner2").remove();
$(".banner3").remove();
$(".banner4").remove();
$(".banner6").remove();
$(".banner7").remove();
$(".banner8").remove();
$('.banner5').css("display","block");
});