jQuery(document).ready(function($){
$(".banner2").remove();
$(".banner3").remove();
$(".banner4").remove();
$(".banner5").remove();
$(".banner6").remove();
$(".banner7").remove();
$(".banner1").remove();
$('.banner8').css("display","block");
});